project_id = "hcnrucjufjrqcfiiqxzv"

[functions.create-admin]
verify_jwt = false

[functions.blur-faces]
verify_jwt = false

[functions.notify-admin-booking]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false